# Generated by Django 5.2.5 on 2025-08-20 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79991234567'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('planned_date', models.DateTimeField(verbose_name='Планируемая дата')),
                ('agreement', models.BooleanField(verbose_name='Согласие на обработку данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
